<a href = "https://colab.research.google.com/github/flyingzaptop/pyton-colab/blob/main/pr%202.ipynb" target = "_ pary"> <mmg src = "https://colab.research.google.com/assets/colab-badge.svg" alt = "otwórz" https://colab.google.com/assets/colab-badge.svg " </a>

Zaimportuj moduł Numpy

In [1]:
import numpy as np

#Task 1

Utwórz tablicę z liczbami parzystymi od 30 do 70

In [4]:
q1 = np.arange(30,70,2)
print(q1)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


#Task 2
Utwórz tablicę z 10 liczbami między 0 (włączającymi) a 1 (nie włączającą) Patrz dokumentacja

In [8]:
q2 = np.arange(0,1,0.1)
print(q2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Task 4
Napisz funkcję, która przyjmuje macierz rozmiaru NXN i zwraca macierz rozmiaru (n+2) x (n+2), na których krawędzie jest umieszczone 0.

In [16]:
w = 3
l = 3

task = np.random.randint(1,10,(w,l))

zer = np.zeros((w+2,l+2), dtype = int)

zer[1:-1,1:-1] = task


print(zer)



[[0 0 0 0 0]
 [0 6 3 5 0]
 [0 5 7 5 0]
 [0 8 9 7 0]
 [0 0 0 0 0]]


#Task 5
W masie z wyprzedzeniem zmień typ danych. Wytnij typ danych przed i po zmianie

In [17]:
print(task.dtype)
task = task.astype(float)
print(task.dtype)

int64
float64


#Task 6
W tej tablicy wymień elementy równe \ większe \ mniejsze niż var przez -1

In [19]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x[x > var] = 1

x[x < var] = -1

x[x == var] = 0
print(x)


[-1  0 -1 -1 -1  0 -1 -1]


#Task 7
Wymień pominięte wartości macierzy (np.nan) przez -1

Patrz np.isnan

In [20]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

X[np.isnan(X)] = -1
print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Task 8
Utwórz macierz rozmiaru 4x6 z liczbami losowymi. Zmień jego rozmiar na 3x8

In [22]:
rmat = np.random.randint(1,10,(4,6))
print(rmat)
print()
print(rmat.reshape(3,8))

[[2 7 3 8 8 7]
 [3 6 5 1 2 6]
 [1 1 9 2 7 7]
 [9 7 8 1 4 1]]

[[2 7 3 8 8 7 3 6]
 [5 1 2 6 1 1 9 2]
 [7 7 9 7 8 1 4 1]]


#Task 9
Utwórz matrycę 3x4 jednostek. Znajdź średnią arytmetyczną (średnią) każdej kolumny

In [26]:
q3 = np.random.randint(0,10,(3,4))
print(q3)
print()
print(q3.mean(axis = 0))

[[9 1 9 0]
 [1 5 6 3]
 [8 7 4 2]]

[6.         4.33333333 6.33333333 1.66666667]


#Task 10
Utwórz losową matrycę w rozmiarze 5x6. Zaokrąglij wartość jednego znaku po przecinku (np.round). Umieść kolumny, aby wartości w pierwszym rzędzie były sortowane według wzrostu

In [34]:
q4 = np.random.randint(0,10,(5,6))
print(q4)
print()
q4 = np.sort(q4, axis = 1)
print(q4)

[[2 0 2 2 0 9]
 [4 1 9 1 4 3]
 [9 5 6 0 9 5]
 [9 2 9 5 4 7]
 [9 3 3 0 8 1]]

[[0 0 2 2 2 9]
 [1 1 3 4 4 9]
 [0 5 5 6 9 9]
 [2 4 5 7 9 9]
 [0 1 3 3 8 9]]


#Task 11
W tej matrycy znajdź wszystkie elementy o wartości od 3 do 6

Zobacz dokumentację np.logical_and

In [35]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

mask = np.logical_and(X > 3, X < 6)
print(X[mask])

[4 5 5 4]


#Task 12
Utwórz losową matrycę rozmiaru 5x6. Normalizuj kolumny: Odejmij wartość minimalną od każdego elementu stawu i podziel wynik przez różnicę między elementem maksymalnym i minimalnym tej kolumny.

Następnie wszystkie wartości muszą znajdować się w ciągu [0, 1]

In [44]:
rm = np.random.randint(0,100,(5,6))
print(rm)
print()
rm = ((rm - rm.min()) / ((rm.max() - rm.min())))
print(rm.round(2))

[[67 41 63  3 36 58]
 [25 64  3 52 31 83]
 [29 33 76 88 10 37]
 [40 66 63 34 79 93]
 [98 28 98 62 89 98]]

[[0.67 0.4  0.63 0.   0.35 0.58]
 [0.23 0.64 0.   0.52 0.29 0.84]
 [0.27 0.32 0.77 0.89 0.07 0.36]
 [0.39 0.66 0.63 0.33 0.8  0.95]
 [1.   0.26 1.   0.62 0.91 1.  ]]
